[package]
name = "ditto-http"
version = "0.0.1"
edition = "2021"
license = "BSD-3-Clause"

[lib]
doctest = false

[dependencies]
bytes = "1.4"
thiserror = "1.0"
reqwest = { version = "0.11", features = ["stream"] }
async-trait = "0.1"
tokio = "1.25"
futures-util = "0.3"
sha256 = "1.1"
