# One CLI to format the code tree - https://github.com/numtide/treefmt

[formatter.rust]
command = "rustfmt"
options = ["--edition", "2021"]
includes = ["*.rs"]

[formatter.nix]
command = "nixpkgs-fmt"
includes = ["*.nix"]

[formatter.haskell]
command = "ormolu"
options = ["--mode", "inplace", "--check-idempotence"]
includes = ["*.hs"]

[formatter.shell]
command = "sh"
options = [
  "-eucx",
  """
shellcheck --external-sources --source-path=SCRIPTDIR "$@"
shfmt -s -w "$@"
  """,
  "--", # bash swallows the second argument when using -c
]
includes = ["*.sh"]
excludes = ["*/husky.sh"]

[formatter.prettier]
command = "npx"
options = ["prettier", "--write"]
includes = ["*.css", "*.html", "*.js", "*.json", "*.md", "*.ts"]

# Our generated JavaScript (and serde generated JSON)
# doesn't agree with the prettier style!
excludes = [
  "crates/ditto-cli/tests/bootstrapped-projects/**",
  "crates/ditto-cli/tests/example-projects/**",
]
