name: Setup Rust toolchain
runs:
  using: "composite"
  steps:
    - uses: actions-rs/toolchain@v1
      with:
        # Keep this in sync with rust-toolchain.toml!
        # At least until toml toolchains are supported:
        # https://github.com/actions-rs/toolchain/issues/126
        # https://github.com/actions-rs/toolchain/pull/166
        toolchain: nightly-2022-10-13
        profile: minimal
        override: true
