export declare const emptyArray: Array<never>;
export declare const float: number;
export declare const int: number;
export declare const intArray: Array<number>;
export declare const nestedArray: Array<Array<number>>;
export declare const no: boolean;
export declare const string: string;
export declare const unit: undefined;
export declare const yes: boolean;
