[package]
name = "ditto-pkg"
version = "0.0.1"
edition = "2021"
license = "BSD-3-Clause"

[lib]
doctest = false

[dependencies]
tracing = "0.1"
ditto-config = { path = "../ditto-config" }

[dev-dependencies]
