[env]
# https://github.com/rust-lang/cargo/issues/3946#issuecomment-973132993
CARGO_WORKSPACE_DIR = { value = "", relative = true }

[profile.test.package.dprint-core]
# Started hitting this since dprint-core v0.59
# https://github.com/dprint/dprint/blob/0788ba63640cf755f81a939c07f4bf94861c5bf0/crates/core/src/formatting/collections/vec_u32_map.rs#L168-L170
debug-assertions = false