[package]
name = "ditto-cli"
version = "0.0.1"
edition = "2021"
license = "BSD-3-Clause"

[[bin]]
name = "ditto" # defaults to `ditto-cli`
path = "src/main.rs"

[dependencies]
ditto-make = { path = "../ditto-make" }
ditto-lsp = { path = "../ditto-lsp" }
ditto-ast = { path = "../ditto-ast" }
ditto-cst = { path = "../ditto-cst" }
ditto-config = { path = "../ditto-config" }
ditto-fmt = { path = "../ditto-fmt" }
clap = { version = "3.1", features = ["regex"] }
time = "0.3"
miette = { version = "4.7", features = ["fancy"] }
log = "0.4"
toml = "0.5"
flexi_logger = "0.22"
# https://github.com/notify-rs/notify/issues/249
notify = "5.0.0-pre.14"
clearscreen = "1.0"
symlink = "0.1.0"
tokio = { version = "1.18", features = ["full"] }
dirs = "4.0"
tempfile = "3.3"
convert_case = "0.6"
reqwest = { version = "0.11", features = ["stream"] }
zip = { version = "0.6", default-features = false, features = ["deflate"] }  # don't want the `time` feature
indicatif = "0.16"
futures-util = "0.3"
console = "0.15"
serde = "1.0"
serde_json = "1.0"
pathdiff = "0.2"
fs2 = "0.4"
atty = "0.2"
semver = "1.0"
shlex = "1.1"
crossbeam-channel = "0.5"

[build-dependencies]
time = "0.3"
