[package]
name = "snapshot-test"
version = "0.0.1"
edition = "2021"
license = "BSD-3-Clause"

[lib]
proc-macro = true
doctest = false

[dependencies]
regex = "1.5"
quote = "1.0"
syn = { version = "1.0", features = ["full"] }
proc-macro2 = "1.0"
